#!/bin/bash
# shellcheck disable=SC2086
source LOG.sh

log_enter pENV

source sENV.sh

export PROJ_LABEL=$SYS
export PROJ_NET=$SYS_NET

export PROJ_CONT=$SWAG_UI_CONT
export PROJ_CONT_DATA_DIR=$SWAG_UI_CONT_DATA_DIR
export PROJ_CONT_DIR=$SWAG_UI_CONT_DIR
export PROJ_CONT_HOME_DIR=$SWAG_UI_CONT_HOME_DIR
export PROJ_HOST=$SWAG_UI_HOST
export PROJ_HOST_DIR=$SWAG_UI_HOST_DIR
export PROJ_IMG=$SWAG_UI_IMG
export PROJ_PASSWORD=$SWAG_UI_PASSWORD
export PROJ_PORT_EXT=$SWAG_UI_PORT_EXT
export PROJ_PORT_INT=$SWAG_UI_PORT_INT
export PROJ_USER=$SWAG_UI_USER
export PROJ_VOL=$SWAG_UI_VOL
export PROJ_VOL_DIR=$SWAG_UI_VOL_DIR

export PROJ_JSON=$SWAG_UI_JSON

log_exit pENV