@echo off


CALL LOG_ENTER pENV

CALL sENV

SET "PROJ_LABEL=$SYS%"
SET "PROJ_NET=$SYS_NET%"

SET "PROJ_CONT=%JAVA_CONT%"
SET "PROJ_CONT_DATA_DIR=%JAVA_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%JAVA_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%JAVA_CONT_HOME_DIR%"
SET "PROJ_HOST=%JAVA_HOST%"
SET "PROJ_HOST_DIR=%JAVA_HOST_DIR%"
SET "PROJ_IMG=%JAVA_IMG%"
SET "PROJ_PASSWORD=%JAVA_PASSWORD%"
SET "PROJ_PORT_EXT=%JAVA_PORT_EXT%"
SET "PROJ_PORT_INT=%JAVA_PORT_INT%"
SET "PROJ_USER=%JAVA_USER%"
SET "PROJ_VOL=%JAVA_VOL%"
SET "PROJ_VOL_DIR=%JAVA_VOL_DIR%"

SET "PROJ_JSON=%SWAG_UI_JSON%"

CALL LOG_EXIT pENV

