@echo off
CALL LOG log_enter pENV

CALL sENV

SET PROJ_LABEL          =$SYS%
SET PROJ_NET            =$SYS_NET%

SET PROJ_CONT           =%SWAG_UI_CONT%
SET PROJ_CONT_DATA_DIR  =%SWAG_UI_CONT_DATA_DIR%
SET PROJ_CONT_DIR       =%SWAG_UI_CONT_DIR%
SET PROJ_CONT_HOME_DIR  =%SWAG_UI_CONT_HOME_DIR%v
SET PROJ_HOST           =%SWAG_UI_HOST%
SET PROJ_HOST_DIR       =%SWAG_UI_HOST_DIR%
SET PROJ_IMG            =%SWAG_UI_IMG%
SET PROJ_PASSWORD       =%SWAG_UI_PASSWORD%
SET PROJ_PORT_EXT       =%SWAG_UI_PORT_EXT%
SET PROJ_PORT_INT       =%SWAG_UI_PORT_INT%
SET PROJ_USER           =%SWAG_UI_USER%
SET PROJ_VOL            =%SWAG_UI_VOL%
SET PROJ_VOL_DIR        =%SWAG_UI_VOL_DIR%

SET PROJ_JSON           =%SWAG_UI_JSON%

CALL LOG log_exit pENV

